using System;
using System.Collections.Generic;
using Couchbase.Lite;
using ExtendedMemory.DataAccess;
using ExtendedMemory.Models;
using Newtonsoft.Json;
using Xamarin.Forms;


[assembly: Dependency(typeof(MemoryDatabase))]
namespace ExtendedMemory.DataAccess
{
    public class MemoryDatabase : IMemoryDatabase
    {
        Manager manager;
        Database database;

        public MemoryDatabase()
        {
            // This line is required for iOS only
            Couchbase.Lite.Storage.SystemSQLite.Plugin.Register();

            manager = Manager.SharedInstance;
            database = manager.GetDatabase("extendedmemory");
        }

        public Response<string> Save(Memory memory)
        {
            var a = memory.ID.GetType();
            var b = memory.GetType().GetProperties();

            var json = JsonConvert.SerializeObject(memory);

            ///* Create a new document */
            var document = database.CreateDocument();

            /* Save the document to the database */
            document.PutProperties(JsonConvert.DeserializeObject<Dictionary<string, object>>(json));

            /* Log the document ID (generated by the database)
               and properties */
            Console.WriteLine($"Document ID :: {document.Id}");
            Console.WriteLine($"Learning {document.GetProperty("Text")} with {document.GetProperty("People")}");

            return new Response<string>
            {
                IsSuccess = true,
                Item = document.Id
            };
        }

        public List<Memory> Get()
        {
            throw new NotImplementedException();
        }

        public Memory Get(SearchType searchType)
        {
            throw new NotImplementedException();
        }

        public Response<string> Forget(Memory memory)
        {
            throw new NotImplementedException();
        }
    }
}